version: "3"
services:
  aws-backup:
    image: zengoma/docker-alpine-aws-backup
    volumes:
      - ./:/backup
    environment:
      CRON_STRINGS: '* * * * * file=backup$$(date +\%Y-\%m-\%d).tar.gz &&
      /bin/tar -zcvf /$$file /backup &&
      /usr/local/bin/aws s3 mv /$$file s3://${AWS_BACKUP_BUCKET}${AWS_BACKUP_PATH}'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_DEFAULT_OUTPUT: ${AWS_DEFAULT_OUTPUT}
